x-restart-policy: &default-restart-policy
  condition: on-failure
  max_attempts: 50
  window: 30s

services:
    gba-postgres:
        deploy:
            restart_policy: *default-restart-policy
    gba-auth-server:
        depends_on:
            gba-postgres:
                condition: service_healthy
        deploy:
            restart_policy: *default-restart-policy
    gba-admin-server:
        depends_on:
            gba-postgres:
                condition: service_healthy
        deploy:
            restart_policy: *default-restart-policy
    gba-webserver:
        depends_on:
            - gba-auth-server
            - gba-admin-server
        deploy:
            restart_policy: *default-restart-policy