name: Build Auth

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: auth
          sparse-checkout-cone-mode: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true
          cache-dependency-path: auth/go.sum

      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-w -s'

      - name: Test
        run: go test --v --cover --useosfs --race ./...
