name: Deploy Staging

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - id: set-release-version
        run: echo "RELEASE_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - id: build-publish
        uses: bitovi/github-actions-react-to-github-pages@v1.2.4
        with:
          checkout-sparse-checkout: gbajs3
          checkout-sparse-checkout-cone-mode: false
          install_command: cd ./gbajs3 && npm ci
          path: ./gbajs3/dist
        env:
          VITE_GBA_RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
